// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: telemetry.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportUsageAttributeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key must match a telemetry field the extension declared in the registry.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value must be in the allowed set the extension declared for key.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageAttributeRequest) Reset() {
	*x = ReportUsageAttributeRequest{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageAttributeRequest) ProtoMessage() {}

func (x *ReportUsageAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageAttributeRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageAttributeRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ReportUsageAttributeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReportUsageAttributeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReportUsageAttributeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Accepted reports whether the host recorded the value.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageAttributeResponse) Reset() {
	*x = ReportUsageAttributeResponse{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageAttributeResponse) ProtoMessage() {}

func (x *ReportUsageAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageAttributeResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageAttributeResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ReportUsageAttributeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x06azdext\"E\n" +
	"\x1bReportUsageAttributeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\":\n" +
	"\x1cReportUsageAttributeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2u\n" +
	"\x10TelemetryService\x12a\n" +
	"\x14ReportUsageAttribute\x12#.azdext.ReportUsageAttributeRequest\x1a$.azdext.ReportUsageAttributeResponseB/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(*ReportUsageAttributeRequest)(nil),  // 0: azdext.ReportUsageAttributeRequest
	(*ReportUsageAttributeResponse)(nil), // 1: azdext.ReportUsageAttributeResponse
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: azdext.TelemetryService.ReportUsageAttribute:input_type -> azdext.ReportUsageAttributeRequest
	1, // 1: azdext.TelemetryService.ReportUsageAttribute:output_type -> azdext.ReportUsageAttributeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
